name: smart_baby_guard
description: "Smart Baby Guard companion app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
#  flutter_bluetooth_serial: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  vibration: ^3.1.4
  intl: ^0.20.2
  torch_light: ^1.0.0
  google_fonts: ^6.2.1
  flutter_bluetooth_serial: ^0.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/sounds/high_alarm.wav

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  min_sdk_android: 23
  adaptive_icon_background: "#1A237E"
  adaptive_icon_foreground: assets/icon/icon.png

#dependency_overrides:
#  flutter_bluetooth_serial:
#    git:
#      url: https://github.com/edufolly/flutter_bluetooth_serial.git
#      ref: master
